---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
  - name: Debug
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs
    commands:
      - /root/entrypoint.sh
      - sbt -v
    when:
      event:
        - push

  - name: Build
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs
    commands:
      - /root/entrypoint.sh
      - sbt +compile
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt_optimiser_drone
    when:
      event:
        - push

  - name: Publish
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs
    commands:
      - /root/entrypoint.sh
      - sbt +publish
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt_optimiser_drone
    when:
      event:
        - push
    depends_on:
      - Build

  - name: Test
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs
    commands:
      - /root/entrypoint.sh
      - sbt --error +test
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt_optimiser_drone
    when:
      event:
        - push
    depends_on:
      - Build

...
