---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
  - name: Build
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs
    commands:
      - /root/entrypoint.sh
      - sbt +compile
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt-artifactory-robot
    when:
      event:
        - push

  - name: Publish
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs
    commands:
      - /root/entrypoint.sh
      - sbt +publish
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt-artifactory-robot
    when:
      event:
        - push
    depends_on:
      - Build

  - name: Test
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs
    commands:
      - /root/entrypoint.sh
      - sbt --error +test
    environment:
      JAVA_OPTS: -Xmx2g
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt-artifactory-robot
    when:
      event:
        - push
    depends_on:
      - Build

  - name: slack_notification
    pull: if-not-exists
    image: plugins/slack
    settings:
      channel: devs
      template: "*{{repo.name}}: _{{build.status}}_*\nCompleted build *{{build.number}}* after *{{since build.started}}* on *{{build.branch}}*\n{{build.link}}\n"
    environment:
      SLACK_WEBHOOK:
        from_secret: slack_webhook
    when:
      status:
        - success
        - failure
      event:
        - push
    depends_on:
      - Test

  - name: analysis
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:v1.0.0
    commands:
      - /root/entrypoint.sh
      - sbt -ivy ./.ivy2 -DdependencyCheckArtifactoryAnalyzerUsername=${DEPENDENCY_CHECK_USERNAME} -DdependencyCheckArtifactoryAnalyzerApiToken=${DEPENDENCY_CHECK_API_TOKEN} dependencyCheck
      - sbt -ivy ./.ivy2 -mem 4096 -J-XX:+UseG1GC clean coverage test coverageReport
    environment:
      DEPENDENCY_CHECK_API_TOKEN:
        from_secret: DEPENDENCY_CHECK_API_TOKEN
      DEPENDENCY_CHECK_USERNAME:
        from_secret: DEPENDENCY_CHECK_USERNAME
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt-artifactory-robot
      ENV_LOG_LEVEL: ERROR
    when:
#      branch: master
      event:
        - push

  - name: sonar-scanner
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/sonar-scanner:v4.6
    commands:
      - sonar-scanner -Dsonar.projectVersion=B${DRONE_BUILD_NUMBER}
    environment:
      DRONE_BUILD_NUMBER: ${DRONE_BUILD_NUMBER}
    when:
      branch:
        - ${DRONE_BRANCH}
      event:
        - push
    depends_on:
      - analysis
...
