---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
  - name: Build
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs
    commands:
      - /root/entrypoint.sh
      - sbt +compile
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt-artifactory-robot
    when:
      event:
        - push

  - name: Publish
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs
    commands:
      - /root/entrypoint.sh
      - sbt +publish
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt-artifactory-robot
    when:
      event:
        - push
    depends_on:
      - Build

  - name: Test
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs
    commands:
      - /root/entrypoint.sh
      - sbt --error +test
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt-artifactory-robot
    when:
      event:
        - push
    depends_on:
      - Build

  - name: slack_notification
    pull: if-not-exists
    image: plugins/slack
    settings:
      channel: devs
      template: "*{{repo.name}}: _{{build.status}}_*\nCompleted build *{{build.number}}* after *{{since build.started}}* on *{{build.branch}}*\n{{build.link}}\n"
    environment:
      SLACK_WEBHOOK:
        from_secret: slack_webhook
    when:
      status:
        - success
        - failure
      event:
        - push
    depends_on:
      - Test
...
