---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
  - name: Build library
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:v1.4.0-debian12-jdk17-node20
    commands:
      - /root/entrypoint.sh
      - sbt -debug +compile
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt_ci
    when:
      event:
        - push

  - name: Unit tests
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:v1.4.0-debian12-jdk17-node20
    commands:
      - /root/entrypoint.sh
      - sbt --error +test
    environment:
      JAVA_OPTS: -Xmx2g
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt_ci
    when:
      event:
        - push
    depends_on:
      - Build library

  - name: Publish library
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:v1.4.0-debian12-jdk17-node20
    commands:
      - /root/entrypoint.sh
      - sbt +publish
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt_ci
    when:
      event:
        - push
    depends_on:
      - Unit tests

  - name: Slack notification
    pull: if-not-exists
    image: plugins/slack
    settings:
      channel: devs
      template: "*{{repo.name}}: _{{build.status}}_*\nCompleted build *{{build.number}}* after *{{since build.started}}* on *{{build.branch}}*\n{{build.link}}\n"
    environment:
      SLACK_WEBHOOK:
        from_secret: slack_webhook
    when:
      status: [ success, failure ]
      event:
        - push
    depends_on:
      - Unit tests

  - name: Code coverage report
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:v1.4.0-debian12-jdk17-node20
    commands:
      - /root/entrypoint.sh
      - sbt -mem 4096 --error clean coverage test coverageReport
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt_ci
      ENV_LOG_LEVEL: ERROR
    when:
      event:
        - push
#      branch:
#        - master
    depends_on:
      - Unit tests

  - name: Scapegoat
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:v1.4.0-debian12-jdk17-node20
    commands:
      - /root/entrypoint.sh
      - sbt scapegoat | true
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt_ci
      ENV_LOG_LEVEL: ERROR
    when:
      event:
        - push
      branch:
        - master
    depends_on:
      - Code coverage report

  - name: Dependency check
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:v1.4.0-debian12-jdk17-node20
    commands:
      - /root/entrypoint.sh
      - sbt -Dlog4j2.level=info dependencyCheck
    environment:
      JAVA_OPTS: -Xmx2g
      NVD_API_KEY:
        from_secret: NVD_API_KEY_SECRET
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt_ci
    when:
      branch:
        - master
      event:
        - push
    depends_on:
      - Publish library

  - name: Sonar scanner
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/sonar-scanner:v4.6
    commands:
      - sonar-scanner -Dsonar.projectVersion=B${DRONE_BUILD_NUMBER}
    environment:
      DRONE_BUILD_NUMBER: ${DRONE_BUILD_NUMBER}
    when:
      branch:
        - master
      event:
        - push
    depends_on:
      - Dependency check

...
