pipeline:
  build:
    image: quay.io/ukhomeofficedigital/scala-sbt:latest
    commands:
      - /root/entrypoint.sh
      - sbt --error test
      - sbt clean +publish
    environment:
      - ARTIFACTORY_USERNAME=drt_optimiser_drone
    secrets:
      - ARTIFACTORY_PASSWORD
    when:
      event:
        - push

