---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
  - name: Build
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs
    resources:
      requests:
        cpu: 1000
        memory: "1GiB"
      limits:
        cpu: 1000
        memory: "1GiB"
    commands:
      - /root/entrypoint.sh
      - sbt compile
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt_optimiser_drone
    when:
      event:
        - push

  - name: Test
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs
    resources:
      requests:
        cpu: 1000
        memory: "1GiB"
      limits:
        cpu: 1000
        memory: "1GiB"
    commands:
      - /root/entrypoint.sh
      - sbt --error test
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt_optimiser_drone
    when:
      event:
        - push
    depends_on:
      - Build

  - name: Publish
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs
    resources:
      requests:
        cpu: 1000
        memory: "1GiB"
      limits:
        cpu: 1000
        memory: "1GiB"
    commands:
      - /root/entrypoint.sh
      - sbt clean +publish
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt_optimiser_drone
    when:
      event:
        - push
    depends_on:
      - Test

...
